"""Runtime hook: ensure GdkPixbuf built-in PNG/JPEG loaders work in the bundle.

On Ubuntu 24.04, PNG and JPEG are compiled directly into libgdk-pixbuf-2.0.so
(no libpixbufloader-png.so / libpixbufloader-jpeg.so exist). The external
loader .so files (svg, tiff, gif, etc.) require dependencies like librsvg-2
that may not be fully present in the bundle; trying to dlopen them aborts
the process before built-in PNG can initialise.

PyInstaller ships its own pyi_rth_gdkpixbuf hook that sets GDK_PIXBUF_MODULE_FILE
to sys._MEIPASS/lib/gdk-pixbuf/loaders.cache if that file exists. This custom
hook runs FIRST and writes an empty (header-only) loaders.cache to that path so
the built-in hook rewrites an empty file → GdkPixbuf loads no external modules
and uses only its built-in loaders (PNG, JPEG). This avoids the SIGABRT from
broken external loader dependencies while keeping PNG/JPEG working.
"""
import os
import sys

_cache_path = os.path.join(sys._MEIPASS, 'lib', 'gdk-pixbuf', 'loaders.cache')
_cache_dir = os.path.dirname(_cache_path)

# Create the expected directory and an empty (header-only) loaders.cache.
# The built-in PyInstaller hook will find this file, process it (no-op since
# there are no paths to rewrite), and set GDK_PIXBUF_MODULE_FILE to a temp
# file containing just the header — so no external loaders are loaded.
if not os.path.exists(_cache_path):
    os.makedirs(_cache_dir, exist_ok=True)
    with open(_cache_path, 'w') as _f:
        _f.write('# GdkPixbuf Image Loader Modules file\n'
                 '# Generated by pyi_rth_gdkpixbuf (empty - use built-in loaders only)\n')
