name: publish-on-pypi

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python 3.8
      uses: actions/setup-python@v2.3.1
      with:
        python-version: 3.8

    - name: Install system dependencies
      run: |
        sudo apt-get update -qy
        sudo apt-get install -y \
          libgirepository1.0-dev \
          libcairo2-dev \
          pkg-config \
          python3-dev \
          gir1.2-gtk-3.0 \
          libgtksourceview-4-0

    - name: Install pythonic dependencies
      run: |
        pip install --upgrade pip
        pip install wheel
        pip install -r requirements.txt

    - name: build_c
      run: |
        python setup.py build
        python setup.py install

    - name: package_dist
      run: |
        python setup.py sdist

    - name: Publish package
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
